### PR TITLE
Replace some toasts with snackbars

### PR DESCRIPTION
**Pull request by TheAndroidMaster**
Most of the toasts with snackbars, as well as attaching existing ones to a CoordinatorLayout instead of a DrawerLayout (this was causing multiple messages to appear on top of each other). Toasts from the NavigationDrawerFragment have not been replaced as they are not visible when the drawer is open.

### CODE REVIEW

**Comment by epicstar** [comment]
I looked through this pull request on my lunch break and it's looking good. I think we can fix the navigation drawer bug by making the `CoordinatorLayout` be the parent of the `DrawerLayout` in the activity's xml. Can you try this change and see what happens?

**Comment by TheAndroidMaster** [comment]
@epicstar the DrawerLayout is meant to be the parent of the CoordinatorLayout, messing up the order can cause a few bugs... Obviously it will work fine if I change it now, but it will get annoying if we want to add more features (if we want a transparent status bar, for example).

**Comment by epicstar** [comment]
Why will the `CoordinatorLayout` as a parent cause bugs with something like a transparent status bar?

**Comment by epicstar** [comment]
Hmm... If we put a snackbar for the navigation drawer, how bad would it look in the app?

**Comment by epicstar** [comment]
This is very good investigation. However, I'm going to reject only because this isn't usable and the fragments are changing. I think we should keep investigating this issue once I refactor all the packages in the app.

**Pull request closed without merging**
